.gitignore, config/__init__.py, config/config.cfg.example, core/parser.py, modules/github/__init__.py, unit_test.py
引入 ~github，可查询 github repo 或 用户
在 merge 之前请先帮忙 debug，没有 debug
=> ✨ 💩 GitHub 查询

modules/ptt/__init__.py
=> Try to fix #70

core/elements/message/__init__.py, core/exceptions.py, core/parser/command.py, core/parser/message.py, modules/arcaea/__init__.py, modules/bugtracker/__init__.py, modules/core/__init__.py, modules/cytoid/__init__.py, modules/cytoid/profile.py, modules/github/repo.py, modules/github/search.py, modules/github/user.py, modules/idlist/__init__.py, modules/maimai/__init__.py, modules/mcbbs_news/__init__.py, modules/mcmod/__init__.py, modules/mcplayer/__init__.py, modules/mcv/__init__.py, modules/meme/__init__.py, modules/mod_dl/__init__.py, modules/nintendo_err/__init__.py, modules/ptt/__init__.py, modules/server/__init__.py, modules/user/__init__.py, modules/weekly/__init__.py, modules/wiki/__init__.py
=> Introduce MessageSession.finish

bot.py, bots/aiocqhttp/message.py, bots/aiocqhttp/message_guild.py, bots/aiogram/message.py, bots/discord/message.py, core/builtins/message/__init__.py, core/elements/message/__init__.py, core/elements/temp/__init__.py, core/parser/message.py, core/utils/i18n.py, database/__init__.py, database/tables.py, database/update.py, modules/core/__init__.py, modules/server/__init__.py, modules/wiki/__init__.py
=> Rewrite database function

modules/server/server.py
before
add:19132  √
add 19132  X
now
add:19132  √
add 19132  √
=> robustness++

modules/cytoid/profile.py
Adds missing grades and reorders grades from highest to lowest.
=> Cytoid profile grade fix

modules/cytoid/profile.py
cytoid.io commit:
https://github.com/Cytoid/cytoid.io/commit/5a6e521f46c004f867ea41eaa7e0216c353a8b09
=> Add AA ranks

modules/dice/dice.py
=> 修复dice调节值为负时仍为正

modules/coin/__init__.py, modules/random/__init__.py
=> New Module: Coin

core/utils/http.py
=> feat: get_url params

DEPLOY.md
=> 更新 DEPLOY.md，加入QQ频道相关指引

modules/ncmusic/__init__.py, modules/ncmusic/locales/zh_cn.json
=> 【更新】：给  `ncmusic` 带来新功能

DEPLOY.md, DEPLOY_Docker.md
=> :sparkles: 新增疑难解答板块

bots/matrix/message.py
fix error when checking native permission level of non-admin users
=> fix: fallback to default power level

modules/ask/__init__.py
```
加载模块中发生了以下错误，对应模块未加载：Failed to load modules.ask: 
Traceback (most recent call last):
File "/home/xtex/akari-bot/core/loader/__init__.py", line 51, in load_modules
importlib.import_module(modules)
File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/xtex/akari-bot/modules/ask/__init__.py", line 21, in <module>
from .agent import agent_executor  # noqa: E402
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/xtex/akari-bot/modules/ask/[agent.py](http://agent.py/)", line 8, in <module>
from [modules.ask.tools](http://modules.ask.tools/) import tools
File "/home/xtex/akari-bot/modules/ask/tools/__init__.py", line 7, in <module>
from …
```
=> fix: fix restart error when ask is not configured

bot.py, bots/matrix/bot.py, bots/matrix/client.py
Cherry-pick [b7638ef00a8cf8ebf4190c6dcaddf7fb76fae13a](https://git.exozy.me/xtex/akari-bot/commit/b7638ef00a8cf8ebf4190c6dcaddf7fb76fae13a)
Cherry-pick [8217bd81dfe8a6dc6a7efe0b1fb2f83d866072da](https://git.exozy.me/xtex/akari-bot/commit/8217bd81dfe8a6dc6a7efe0b1fb2f83d866072da)
=> Fix matrix

modules/ask/__init__.py
When openai_api_key is empty:
> openai.OpenAIError: The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable
See-also: https://github.com/Teahouse-Studios/akari-bot/pull/1037
=> Fix ask module loading error

modules/server/server.py
=> :bug: 修复漏洞

bots/aiocqhttp/message.py, bots/lagrange/message.py, config/config.toml.example, core/parser/message.py, docs/DEPLOY.md, docs/DEPLOY_Docker.md
=> OpenShamrock support

core/builtins/message/chain.py
在将`FormattedTime`转换为`Plain`时，如果前一个消息部分也是转换为`Plain`，则直接将`FormattedTime`追加到上一个`Plain`而不是新开一个`Plain`。
（在matrix上，每一条`Plain`都会单独开一条新消息
=> Append text to the end of last plain for FormattedTime

modules/wiki/set.py
=> Fix iw set on platforms with audit unavailable

bots/aiocqhttp/bot.py, bots/aiocqhttp/message.py, config/config.toml.example
=> array post

modules/github/__init__.py, modules/github/locales/zh_cn.json, modules/github/repo.py, modules/github/search.py, modules/github/user.py
=> 支持 GitHub Personal Access Token
